{
 "openapi": "3.0.0",
 "info": {
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "description": "The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://marketplace.zoom.us/docs/guides/auth/oauth) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.\n\nFor instance, you can list all users on a[...]",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "title": "Zoom Phone API",
  "version": "2.0.0"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/phone/audios/{audioId}": {
   "delete": {
    "tags": [
     "Audio Library"
    ],
    "description": "Deletes an audio item.\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:write`,`phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "DeleteAudioItem",
    "summary": "Delete an audio item"
   },
   "get": {
    "tags": [
     "Audio Library"
    ],
    "description": "Gets an audio item.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:read`,`phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "GetAudioItem",
    "summary": "Get an audio item"
   },
   "patch": {
    "tags": [
     "Audio Library"
    ],
    "description": "Updates an audio item.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "UpdateAudioItem",
    "summary": "Update an audio item"
   }
  },
  "/phone/auto_receptionists": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Use this API to list auto receptionists.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listAutoReceptionists",
    "summary": "List auto receptionists"
   },
   "post": {
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Auto receptionists answer calls with a personalized recording and routes calls to a phone user, call queue, common area phone, voicemail or an IVR system. Use this API to add an [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-) to a Zoom Phone\n\n**Prerequisites:**\n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:admin`\n[...]",
    "operationId": "addAutoReceptionist",
    "summary": "Add an auto receptionist"
   }
  },
  "/phone/auto_receptionists/{autoReceptionistId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Use this API to get information on a specific auto receptionist.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getAutoReceptionistDetail",
    "summary": "Get an auto receptionist"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "An auto receptionist answers calls with a personalized recording and routes calls to a phone user, call queue, common area phone, or voicemail. An auto receptionist can also be set up so that it routes calls to an interactive voice response (IVR) system to allow callers to select the routing options.\nUse this API to [change information](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-#h_1d5ffc56-6ba3-4ce5-[...]",
    "operationId": "updateAutoReceptionist",
    "summary": "Update an auto receptionist"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "An auto receptionist answers calls with a personalized recording and routes calls to a phone user, call queue, common area (phone), or to a voicemail. An auto receptionist can also be set up so that it routes calls to an interactive voice response (IVR) system to allow callers to select the routing options.\nUse this API to [delete a non-primary auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response[...]",
    "operationId": "deleteAutoReceptionist",
    "summary": "Delete a non-primary auto receptionist"
   }
  },
  "/phone/auto_receptionists/{autoReceptionistId}/policies": {
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Use this API to update the policy setting of a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "updateAutoReceptionistPolicy",
    "summary": "Update an auto receptionist policy"
   },
   "get": {
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Use this API to get the policy setting of a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-).\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getAutoReceptionistsPolicy",
    "summary": "Get an auto receptionist policy"
   }
  },
  "/phone/auto_receptionists/{autoReceptionistId}/policies/{policyType}": {
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Use this API to update the policy sub-setting of a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-) according to the policy type. For example, you can update shared access members.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone license\n* Account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.[...]",
    "operationId": "updatePolicy",
    "summary": "Update a policy setting"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Use this API to add a policy sub-setting according to the policy type for a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). For example, you can set up shared access members.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone license\n* Account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/d[...]",
    "operationId": "AddPolicy",
    "summary": "Add a policy setting"
   },
   "delete": {
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Use this API to remove the policy sub-setting of a [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). For example, you can remove shared access members.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone license\n* Account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate[...]",
    "operationId": "DeletePolicy",
    "summary": "Delete a policy setting"
   }
  },
  "/phone/auto_receptionists/{autoReceptionistId}/ivr": {
   "get": {
    "tags": [
     "IVR"
    ],
    "description": "Gets an [interactive voice response (IVR) system](https://support.zoom.us/hc/en-us/articles/360038601971) of the specified auto receptionist.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "getAutoReceptionistIVR",
    "summary": "Get auto receptionist IVR"
   },
   "patch": {
    "tags": [
     "IVR"
    ],
    "description": "Updates the [interactive voice response (IVR) system](https://support.zoom.us/hc/en-us/articles/360038601971) of the specified auto receptionist.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "updateAutoReceptionistIVR",
    "summary": "Update auto receptionist IVR"
   }
  },
  "/phone/auto_receptionists/{autoReceptionistId}/phone_numbers": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Unassign all phone numbers that were previously assigned to an [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions<br>\n**Scopes:** `phone:write:admin`<br> \n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
    "operationId": "unassignAllPhoneNumsAutoReceptionist",
    "summary": "Unassign all phone numbers"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Assign available phone numbers to an [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). The available numbers can be retrieved using the List Phone Numbers API with `type` query parameter set to \"unassigned\".\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions<br>\n**Scopes:** `phone:write:admin`<br> \n\n\n **[Rate Limit Lab[...]",
    "operationId": "assignPhoneNumbersAutoReceptionist",
    "summary": "Assign phone numbers"
   }
  },
  "/phone/auto_receptionists/{autoReceptionistId}/phone_numbers/{phoneNumberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Auto Receptionists"
    ],
    "description": "Unassign a specific phone number that was previously assigned to an [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions<br>\n**Scopes:** `phone:write:admin`<br> \n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "unassignAPhoneNumAutoReceptionist",
    "summary": "Unassign a phone number"
   }
  },
  "/phone/batch_locations": {
   "post": {
    "tags": [
     "Emergency Service Locations"
    ],
    "description": "Batches the add emergency service locations.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n* Account owner or admin permissions\n\n**Scope:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "batchAddLocations",
    "summary": "Batch add emergency service locations"
   }
  },
  "/phone/blocked_list": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Blocked List"
    ],
    "description": "A Zoom account owner or a user with admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers). Blocked callers will hear a generic message stating that the person they are calling is not available. \nUse this API to list all the blocked lists in an acccount.\n\n**Prerequisites:**\n* Pro or higher account plan with[...]",
    "operationId": "listBlockedList",
    "summary": "List blocked lists"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Blocked List"
    ],
    "description": "A Zoom account owner or a user with the admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers). Blocked callers will hear a generic message stating that the person they are calling is not available. Use this API to create a block list and add a number to the list.\n\n**Prerequisites:**\n* Pro or higher account [...]",
    "operationId": "addAnumberToBlockedList",
    "summary": "Create a blocked list"
   }
  },
  "/phone/blocked_list/{blockedListId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Blocked List"
    ],
    "description": "A Zoom account owner or a user with admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers).\n\nUse this API to delete a blocked list and therefore removing the associated number from the blocked list. The number will be unblocked after the deletion.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom [...]",
    "operationId": "deleteABlockedList",
    "summary": "Delete a blocked list"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Blocked List"
    ],
    "description": "A Zoom account owner or a user with admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers). Blocked callers will hear a generic message stating that the person they are calling is not available.\nUse this API to get information about a specific blocked list.\n\n**Prerequisites:**\n* Pro or higher account plan w[...]",
    "operationId": "getABlockedList",
    "summary": "Get blocked list details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Blocked List"
    ],
    "description": "A Zoom account owner or a user with admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers). Blocked callers will hear a generic message stating that the person they are calling is not available.\nUse this API to update the information on the blocked list.\n\n**Prerequisites:**\n* Pro or higher account plan with[...]",
    "operationId": "updateBlockedList",
    "summary": "Update a blocked list"
   }
  },
  "/phone/byoc_numbers": {
   "post": {
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to add BYOC (Bring Your Own Carrier) phone numbers to Zoom Phone.\n\n**Scopes:** `phone:write:admin`, `phone:write`, or `phone:master`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise plan \n* A Zoom Phone license",
    "operationId": "addBYOCNumber",
    "summary": "Add BYOC phone numbers"
   }
  },
  "/phone/call_logs": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Logs"
    ],
    "description": "Returns an account's [call logs](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-Call-Logs).\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license \n* Account owner or a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) with Zoom Phone management\n\n**Scopes:** `phone:read:admin`, `phone_call_log:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits/#zo[...]",
    "operationId": "accountCallLogs",
    "summary": "Get account's call logs"
   }
  },
  "/phone/call_logs/{callLogId}": {
   "get": {
    "tags": [
     "Call Logs"
    ],
    "description": "Returns information about a [call log](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-and-identifying-logs).\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`, `phone_call_log:read`, `phone_call_log:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits/#zoom-phone-apis):** `Light`",
    "operationId": "getCallLogDetails",
    "summary": "Get call log details",
    "x-private": false
   }
  },
  "/phone/call_logs/{callLogId}/client_code": {
   "put": {
    "tags": [
     "Call Logs"
    ],
    "description": "Adds a client code to a [call log](https://support.zoom.us/hc/en-us/articles/360040999352-Assigning-client-codes-to-phone-calls). You can track call logs with a client code. \n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits/#zoom-phone-apis):** `Light`",
    "operationId": "addClientCodeToCallLog",
    "summary": "Add a client code to a call log"
   }
  },
  "/phone/call_logs/{id}/recordings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Recordings"
    ],
    "description": "Gets an account's call recording(https://support.zoom.us/hc/en-us/articles/360038521091-Accessing-and-sharing-call-recordings) by the recording's `callId` or `callLogId` ID.\n\n**Prerequisites:** \n* A Pro or higher account with Zoom Phone license. \n* Account owner or admin privileges\n\n**Scopes:** `phone:read:admin`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "getPhoneRecordingsByCallIdOrCallLogId",
    "summary": "Get recording by call ID"
   }
  },
  "/phone/call_queues": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service etc.\n Use this API to list Call queues.\n\n\n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n \n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs[...]",
    "operationId": "listCallQueues",
    "summary": "List call queues"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service etc.\n Use this API to [create a call queue](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues#h_e81faeeb-9184-429a-aaea-df49ff5ff413).\n You can add phone users or common area phones to call queues.\n\n**Prerequisites:**\n\n* Pro, Busi[...]",
    "operationId": "createCallQueue",
    "summary": "Create a call queue"
   }
  },
  "/phone/call_queues/{callQueueId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service etc.\n Use this API to delete a Call Queue.\n \n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n \n\n\n **[Rate Limit Label](https://marketplace.zoom.us/d[...]",
    "operationId": "deleteACallQueue",
    "summary": "Delete a call queue"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service etc.\n Use this API to get information on a specific Call Queue.\n\n \n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n \n\n\n **[Rate Limit Label](https:/[...]",
    "operationId": "getACallQueue",
    "summary": "Get call queue details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service etc.\n Use this API to update information of a specific Call Queue.\n \n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n \n\n **[Rate Limit Label](https:/[...]",
    "operationId": "updateCallQueue",
    "summary": "Update call queue details"
   }
  },
  "/phone/call_queues/{callQueueId}/manager": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "A call queue manager has the privileges to manage the call queue's voicemail inbox and recordings, change all call queue settings and call queue policy settings.\n\n Use this API to to set another phone user as the [call queue manager](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues#h_db06854b-e6a3-4afe-ba15-baf58f31f90c).\n\n\n**Prerequisites:**\n* Pro or higher account plan.\n* Account owner or admin permissions\n* Zoom Phone license\n\n**Scopes:[...]",
    "operationId": "changeCallQueueManager",
    "deprecated": true,
    "summary": "Change call queue manager"
   }
  },
  "/phone/call_queues/{callQueueId}/members": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Lists the call queue members.\n\n\n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n \n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n",
    "operationId": "listCallQueueMembers",
    "summary": "List call queue members"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Use this API to remove all members from a Call Queue who were previously assigned to that Call Queue. The members could be phone users or [common area phones](https://support.zoom.us/hc/en-us/articles/360028516231-Managing-Common-Area-Phones).\n**Prerequisites:**\n\n* Pro or higher account plan.\n* Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n \n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "unassignAllMembers",
    "summary": "Unassign all members"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Add phone users and/or [common areas](https://support.zoom.us/hc/articles/4481136653709) as members to a specific call queue.\n\n**Prerequisites:**\n* Pro or higher account plan.\n* Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addMembersToCallQueue",
    "summary": "Add members to a call queue"
   }
  },
  "/phone/call_queues/{callQueueId}/members/{memberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Use this API to remove a member who was previously added to a call queue. The member could be a phone user, [common area phone](https://support.zoom.us/hc/en-us/articles/360028516231-Managing-Common-Area-Phones) or common area. Note that you cannot use this API to unassign a call queue manager. \n**Prerequisites:**\n\n* Pro or higher account plan.\n* Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/[...]",
    "operationId": "unassignMemberFromCallQueue",
    "summary": "Unassign a member"
   }
  },
  "/phone/call_queues/{callQueueId}/phone_numbers": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Use this API to unbind all phone numbers that are assigned to a [Call Queue](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues) After successful unbinding, the numbers will appear in the [Unassigned tab](https://zoom.us/signin#/numbers/unassigned).\n If you only need to unassign a specific phone number, use the Unassign a Phone Number API instead. \n\n**Prerequisites:**\n* Pro or higher account palan\n* Account owner or admin permissions\n* Zoom Phon[...]",
    "operationId": "unassignAPhoneNumCallQueue",
    "summary": "Unassign all phone numbers"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "After [buying phone number(s)](https://support.zoom.us/hc/en-us/articles/360020808292#h_007ec8c2-0914-4265-8351-96ab23efa3ad), you can assign it, allowing callers to directly dial a number to reach a [call queue](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues).\n\n\n**Prerequisites:**\n\n* Pro or higher account plan.\n* Account owner or admin permissions\n* Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n \n **[Rate Limit Label](https://mar[...]",
    "operationId": "assignPhoneToCallQueue",
    "summary": "Assign numbers to a call queue"
   }
  },
  "/phone/call_queues/{callQueueId}/phone_numbers/{phoneNumberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "After assigning a phone number, you can unbind it if you don't want it to be assigned to a [Call Queue](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues). Use this API to unbind a phone number from a Call Queue. After successful unbinding, the number will appear in the [Unassigned tab](https://zoom.us/signin#/numbers/unassigned).\n\n\n**Prerequisites:**\n* Pro or higher account palan\n* Account owner or admin permissions\n* Zoom Phone license \n **S[...]",
    "operationId": "unAssignPhoneNumCallQueue",
    "summary": "Unassign a phone number"
   }
  },
  "/phone/call_queues/{callQueueId}/recordings": {
   "get": {
    "tags": [
     "Call Queues"
    ],
    "description": "Use this API to view [call recordings](https://support.zoom.us/hc/en-us/articles/360038521091#h_cbc9f2a3-e06c-4daa-83d4-ddbceef9c77b) from the call queue.\n\n\n**Prerequisites:**\n\n* Pro or higher account with Zoom Phone license.\n* [Automatic call recordings](https://support.zoom.us/hc/en-us/articles/360033511872#h_fcb297bb-14e8-4094-91ca-dc61e1a18734) must be enabled in the Policy Settings for call queues. \n **Scope:** `phone:read:admin`\n **[Rate Limit Label](https://mar[...]",
    "operationId": "getCallQueueRecordings",
    "summary": "Get call queue recordings"
   }
  },
  "/phone/call_queues/{callQueueId}/policies/{policyType}": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Use this API to add the policy sub-setting for a specific [call queue](https://support.zoom.us/hc/en-us/articles/360021524831) according to the `policyType`. For example, you can use this API to set up shared access members. \n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`"[...]",
    "operationId": "addCQPolicySubSetting",
    "summary": "Add a policy setting to a call queue"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Use this API to update the policy sub-setting for a specific [call queue](https://support.zoom.us/hc/en-us/articles/360021524831) according to the `policyType`. For example, you can use this API to update shared access members.\n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light[...]",
    "operationId": "updateCQPolicySubSetting",
    "summary": "Update a CQ policy setting"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Queues"
    ],
    "description": "Use this API to remove the policy sub-setting for a specific [call queue](https://support.zoom.us/hc/en-us/articles/360021524831) according to the `policyType`. For example, you can use this API to remove shared access members. \n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Ligh[...]",
    "operationId": "removeCQPolicySubSetting",
    "summary": "Delete a CQ policy setting"
   }
  },
  "/phone/calling_plans": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Plans"
    ],
    "description": "Use this API to return all of an account's Zoom Phone [calling plans](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans).\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro or a higher account \n* A Zoom Phone license",
    "operationId": "listCallingPlans",
    "summary": "List calling plans"
   }
  },
  "/phone/plans": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Plans"
    ],
    "description": "Use this API to return all of an account's Zoom Phone [plan package](https://marketplace.zoom.us/docs/api-reference/other-references/plans#additional-zoom-phone-plans-and-codes), phone number usage and availability.\n\n**Prerequisites:** \n* A Pro or a higher account \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listPhonePlans",
    "summary": "List plan information"
   }
  },
  "/phone/carrier_reseller/numbers": {
   "get": {
    "tags": [
     "Carrier Reseller"
    ],
    "description": "Use this API to list phone numbers in a carrier reseller (master) account that can be pushed to its subaccounts.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "listCRPhoneNumbers",
    "summary": "List phone numbers"
   },
   "patch": {
    "tags": [
     "Carrier Reseller"
    ],
    "description": "Use this API to change phone number status to 'active' in a carrier reseller's master account. Up to 200 numbers at a time.\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "activeCRPhoneNumbers",
    "summary": "Activate phone numbers"
   },
   "post": {
    "tags": [
     "Carrier Reseller"
    ],
    "description": "Use this API to add phone numbers to a carrier reseller (master) account. Up to 200 numbers at a time. If this API is called in MA mode, it also has functions of distribution.\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "createCRPhoneNumbers",
    "summary": "Create phone numbers"
   }
  },
  "/phone/carrier_reseller/numbers/{number}": {
   "delete": {
    "tags": [
     "Carrier Reseller"
    ],
    "description": "Use this API to delete or unassign a phone number from a carrier reseller account.\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "deleteCRPhoneNumber",
    "summary": "Delete a phone number"
   }
  },
  "/phone/common_area_phones": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "Use this API to list all of an account's [common area phones](https://support.zoom.us/hc/en-us/articles/360028516231-Managing-Common-Area-Phones).\n\nA common area phone can be provisioned by a Zoom account owner or a Zoom admin so that anyone in an organization can use it. For example, if your office has shared desks that don't belong to a specific employees, you could add a common area phone so that any person can use it.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Lab[...]",
    "operationId": "listCommonAreaPhones",
    "deprecated": true,
    "summary": "List common area phones"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "Use this API to [add a common area phone](https://support.zoom.us/hc/en-us/articles/360028516231-Managing-Common-Area-Phones#h_2d0da347-c35a-4993-9771-e21aaa568deb).\n\nA common area phone can be provisioned by a Zoom account owner or a Zoom admin so that anyone in an organization can use it. For example, if your office has shared desks that don't belong to a specific employees, you could add a common area phone so that any person can use it.\n\n**Prerequisites:**\n\n* Pro or[...]",
    "operationId": "addCommonAreaPhone",
    "deprecated": true,
    "summary": "Add a common area phone"
   }
  },
  "/phone/common_area_phones/{commonAreaPhoneId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "A common area phone can be provisioned by a Zoom account owner or a Zoom admin so that anyone in an organization can use it. For example, if your office has shared desks that don't belong to a specific employees, you could add a common area phone so that any person can use it.\n Use this API to remove the [common area phone](https://support.zoom.us/hc/en-us/articles/360028516231-Managing-Common-Area-Phones) from Zoom Phone System in an account.\n\n**Prerequisites:**\n\n* Pro [...]",
    "operationId": "deleteCommonAreaPhone",
    "deprecated": true,
    "summary": "Delete a common area phone"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "Use this API to get details on a specific [common area phone](https://support.zoom.us/hc/en-us/articles/360028516231-Managing-Common-Area-Phones) in an account.\n\nA common area phone can be provisioned by a Zoom account owner or a Zoom admin so that anyone in an organization can use it. For example, if your office has shared desks that don't belong to a specific employees, you could add a common area phone so that any person can use it. \n\n\n\n**Prerequisites:**\n\n* Pro or[...]",
    "operationId": "getACommonAreaPhone",
    "deprecated": true,
    "summary": "Get common area phone details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "Use this API to update details on a specific [common area phone](https://support.zoom.us/hc/en-us/articles/360028516231-Managing-Common-Area-Phones) in an account.\n\nA common area phone can be provisioned by a Zoom account owner or a Zoom admin so that anyone in an organization can use it. For example, if your office has shared desks that don't belong to a specific employees, you could add a common area phone so that any person can use it.\n\n**Scopes:** `phone:write:admin`\[...]",
    "operationId": "updateCommonAreaPhone",
    "deprecated": true,
    "summary": "Update common area phone"
   }
  },
  "/phone/common_area_phones/{commonAreaPhoneId}/calling_plans": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "Assign calling plans to common area phone.\n\n\n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scopes:** `phone:write:admin`\n \n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "assignCallingPlansToCommonAreaPhone",
    "deprecated": true,
    "summary": "Assign calling plans to common area phone"
   }
  },
  "/phone/common_area_phones/{commonAreaPhoneId}/calling_plans/{type}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "Use this API to unassign a calling plan from a common area phone.\n\n**Prerequisites:** \n* A Pro or higher account with a Zoom Phone license \n* An account owner or admin permissions\n\n**Scopes:** \n `phone:write:admin`\n\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "unassignCallingPlansFromCommonAreaPhone",
    "deprecated": true,
    "summary": "Unassign calling plan from a common area phone"
   }
  },
  "/phone/common_area_phones/{commonAreaPhoneId}/phone_numbers": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "Assign phone numbers to common area phone.\n\n\n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n**Scope:** `phone:write:admin`\n \n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "assignPhoneNumbersToCommonAreaPhone",
    "deprecated": true,
    "summary": "Assign phone numbers to common area phone"
   }
  },
  "/phone/common_area_phones/{commonAreaPhoneId}/phone_numbers/{phoneNumberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Area Phones"
    ],
    "description": "Use this API to unassign a phone number from a common Area phone.\n\n**Prerequisites:**\n\n* A Pro or a higher account with a Zoom Phone license\n* An account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "unassignPhoneNumbersFromCommonAreaPhone",
    "deprecated": true,
    "summary": "Unassign phone numbers from a common area phone"
   }
  },
  "/phone/common_areas": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to list common areas under an account.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listCommonAreas",
    "summary": "List common areas"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to add an instance of common area. Configure devices shared by users and deployed in shared spaces.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addCommonArea",
    "summary": "Add a common area"
   }
  },
  "/phone/common_areas/{commonAreaId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to remove the common area. \n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteCommonArea",
    "summary": "Delete a common area"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to get detailed information on the common area.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**<br>\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**Scopes:** `phone:read:admin`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "getACommonArea",
    "summary": "Get common area details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to update the common area information.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "updateCommonArea",
    "summary": "Update common area"
   }
  },
  "/phone/common_areas/{commonAreaId}/calling_plans": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to assign calling plans to a common area.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scope:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "assignCallingPlansToCommonArea",
    "summary": "Assign calling plans to a common area"
   }
  },
  "/phone/common_areas/{commonAreaId}/calling_plans/{type}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to unassign a calling plan from the common area.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:** \n* A Pro or higher account with a Zoom Phone license \n* An account owner or admin permissions \n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "unassignCallingPlansFromCommonArea",
    "summary": "Unassign a calling plan from the common area"
   }
  },
  "/phone/common_areas/{commonAreaId}/phone_numbers": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Assign phone numbers to a common area.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scope:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "assignPhoneNumbersToCommonArea",
    "summary": "Assign phone numbers to a common area"
   }
  },
  "/phone/common_areas/{commonAreaId}/phone_numbers/{phoneNumberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to unassign a phone number from a common area.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* A Pro or a higher account with a Zoom Phone license\n* An account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "unassignPhoneNumbersFromCommonArea",
    "summary": "Unassign phone numbers from common area"
   }
  },
  "/phone/common_areas/{commonAreaId}/settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to get common area settings.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scope:** `phone:read:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "getCommonAreaSettings",
    "summary": "Get common area settings"
   }
  },
  "/phone/common_areas/{commonAreaId}/settings/{settingType}": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to add the common area setting according to the setting type, specifically for desk phones.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scope:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "AddCommonAreaSetting",
    "summary": "Add common area settings"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to remove the common area subsetting from desk phones. \n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteCommonAreaSetting",
    "summary": "Delete common area setting"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Common Areas"
    ],
    "description": "Use this API to update the common area setting according to the setting type, specifically for desk phones.\n\n**Note**: For use by customers who opted for `Common Area Optimization`  \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n**Scope:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "UpdateCommonAreaSetting",
    "summary": "Update common area settings"
   }
  },
  "/phone/company_number": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Settings"
    ],
    "description": "Use this API to [change an account's main company number](https://support.zoom.us/hc/en-us/articles/360028553691#h_82414c34-9df2-428a-85a4-efcf7f9e0d72).\n\nExternal users can use the [main company number](https://support.zoom.us/hc/en-us/articles/360028553691) to reach your Zoom Phone users by dialing the main company number and the user's extension. It can also be used by your account's Zoom Phone users as their caller ID when making calls.\n\n**Scopes:** `phone:write:admin[...]",
    "operationId": "changeMainCompanyNumber",
    "summary": "Change main company number"
   }
  },
  "/phone/devices": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Devices"
    ],
    "description": "List all the [desk phone devices](https://support.zoom.us/hc/en-us/articles/360021119092) that are configured with Zoom Phone on an account.\n\n**Scopes:** `phone:read:admin`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions",
    "operationId": "listPhoneDevices",
    "summary": "List devices"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Devices"
    ],
    "description": "By default, all Zoom Phone users can make and receive calls using the Zoom desktop and mobile applications. Additionally, if a desk phone is required, use this API to [add a desk phone and assign it](https://support.zoom.us/hc/en-us/articles/360021119092#h_5ca07504-68a8-4c3d-ad0e-c1d3594436da) to a user.\n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n* [Supported device](https://support.zoom.us/hc/en-us/articl[...]",
    "operationId": "addPhoneDevice",
    "summary": "Add a device"
   }
  },
  "/phone/devices/sync": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Devices"
    ],
    "description": "Use this API to resync all online zero-touch or assisted-provisioning devices in an account or a site. Only allows sending one request every 15 minutes.\n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "syncPhoneDevice",
    "summary": "Sync deskphones"
   }
  },
  "/phone/devices/{deviceId}/reboot": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Devices"
    ],
    "description": "Use this API to reboot an online zero-touch or assisted-provisioning device. You can only send one request every second.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions. \n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "rebootPhoneDevice",
    "summary": "Reboot a desk phone"
   }
  },
  "/phone/devices/{deviceId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Devices"
    ],
    "description": "Remove a [desk phone device or ATA (Analog Telephone Adapter)](https://support.zoom.us/hc/en-us/articles/360021119092) from the Zoom Phone System Management.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n* Device must not have been assigned to a user.\n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteADevice",
    "summary": "Delete a device"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Devices"
    ],
    "description": "Gets detailed information about a specific [desk phone device](https://support.zoom.us/hc/en-us/articles/360021119092).\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions",
    "operationId": "getADevice",
    "summary": "Get device details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Devices"
    ],
    "description": "Update information of a [desk phone device](https://support.zoom.us/hc/en-us/articles/360021119092).\n\n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n \n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "updateADevice",
    "summary": "Update a device"
   }
  },
  "/phone/devices/{deviceId}/extensions/{extensionId}": {
   "delete": {
    "tags": [
     "Phone Devices"
    ],
    "description": "Use this API to unassign a specific assignee from the device.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions. \n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteExtensionFromADevice",
    "summary": "Unassign an entity from the device"
   }
  },
  "/phone/devices/{deviceId}/extensions": {
   "post": {
    "tags": [
     "Phone Devices"
    ],
    "description": "By default, all Zoom Phone users can make and receive calls using the Zoom desktop and mobile applications. Additionally, if a desk phone is required, use this API to [add a desk phone and assign it to a user](https://support.zoom.us/hc/en-us/articles/360021119092#h_5ca07504-68a8-4c3d-ad0e-c1d3594436da).\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n* [Supported device](https://support.zoom.us/hc/en-us/articles[...]",
    "operationId": "addExtensionsToADevice",
    "summary": "Assign an entity to a device"
   }
  },
  "/phone/devices/{deviceId}/line_keys": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Device Line Keys"
    ],
    "description": "Use this API to get information on the Zoom Phone device [line keys](https://support.zoom.us/hc/en-us/articles/4402415568397-Customizing-keys-for-devices-with-multiple-users) settings and position.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin` or `phone:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "listDeviceLineKeySetting",
    "summary": "Get device line keys information"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Device Line Keys"
    ],
    "description": "Use this API to batch update the Zoom Phone device [line key position](https://support.zoom.us/hc/en-us/articles/4402415568397-Customizing-keys-for-devices-with-multiple-users) information.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin` or `phone:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "batchUpdateDeviceLineKeySetting",
    "summary": "Batch update device line key position"
   }
  },
  "/phone/emergency_addresses": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Emergency Addresses"
    ],
    "description": "Lists the emergency addresses.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "listEmergencyAddresses",
    "summary": "List emergency addresses"
   },
   "post": {
    "tags": [
     "Emergency Addresses"
    ],
    "description": "Adds an emergency address. If the address provided is not an exact match, the system generated corrected address will be used. \n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "addEmergencyAddress",
    "summary": "Add an emergency address"
   }
  },
  "/phone/emergency_addresses/{emergencyAddressId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Emergency Addresses"
    ],
    "description": "Removes an emergency address.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "deleteEmergencyAddress",
    "summary": "Delete an emergency address"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Emergency Addresses"
    ],
    "description": "Gets the emergency address information.\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions<br>",
    "operationId": "getEmergencyAddress",
    "summary": "Get emergency address details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Emergency Addresses"
    ],
    "description": "Updates an emergency address information. If the address provided is not an exact match, the system generated corrected address will be used. \n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "updateEmergencyAddress",
    "summary": "Update an emergency address"
   }
  },
  "/phone/emergency_number_pools/phone_numbers": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to assign phone numbers to the [Emergency Number Pool](https://support.zoom.us/hc/en-us/articles/360062110192-Routing-emergency-calls).\n\n**Scopes:** `phone:write`, `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "assignPhoneNumberToEmergencyNumberPool",
    "summary": "Assign phone numbers to the emergency number pool"
   }
  },
  "/phone/emergency_number_pools/phone_numbers/{phoneNumberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to unassign phone numbers from the [Emergency Number Pool](https://support.zoom.us/hc/en-us/articles/360062110192-Routing-emergency-calls).\n\n**Scopes:** `phone:write`, `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "unassignPhoneNumberFromEmergencyNumberPool",
    "summary": "Unassign phone numbers from the emergency number pool"
   }
  },
  "/phone/extension/{extensionId}/call_handling/settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Handling"
    ],
    "description": "Gets information about a Zoom Phone's call handling settings. Call handling settings let you control how your system routes calls during business, closed, or holiday hours. For more information, read our [API guide](https://marketplace.zoom.us/docs/guides/zoom-phone/call-handling/) or Zoom support article [Customizing call handling settings](https://support.zoom.us/hc/en-us/articles/360059966372-Customizing-call-handling-settings).\n\n**Applicable to user, call queue, or auto[...]",
    "operationId": "getCallHandling",
    "summary": "Get call handling settings"
   }
  },
  "/phone/extension/{extensionId}/call_handling/settings/{settingType}": {
   "delete": {
    "tags": [
     "Call Handling"
    ],
    "description": "Deletes a Zoom Phone's call handling settings. Call handling settings let you control how your system routes calls during business, closed, or holiday hours. For more information, read our [API guide](https://marketplace.zoom.us/docs/guides/zoom-phone/call-handling/) or Zoom support article [Customizing call handling settings](https://support.zoom.us/hc/en-us/articles/360059966372-Customizing-call-handling-settings).\n\n**Applicable to user, call queue, or auto receptionist c[...]",
    "operationId": "deleteCallHandling",
    "summary": "Delete a call handling setting"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Handling"
    ],
    "description": "Updates a Zoom Phone's call handling setting. Call handling settings let you control how your system routes calls during business, closed, or holiday hours. For more information, read our [API guide](https://marketplace.zoom.us/docs/guides/zoom-phone/call-handling/) or Zoom support article [Customizing call handling settings](https://support.zoom.us/hc/en-us/articles/360059966372-Customizing-call-handling-settings).\n\n**Applicable to user, call queue, or auto receptionist ca[...]",
    "operationId": "updateCallHandling",
    "summary": "Update a call handling setting"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Handling"
    ],
    "description": "Adds Zoom Phone call handling subsettings for your phone system. Call handling settings let you control how your system routes calls during business, closed, or holiday hours. For more information, read our [API guide](https://marketplace.zoom.us/docs/guides/zoom-phone/call-handling/) or Zoom support article [Customizing call handling settings](https://support.zoom.us/hc/en-us/articles/360059966372-Customizing-call-handling-settings).\n\n**Applicable to user, call queue, or a[...]",
    "operationId": "addCallHandling",
    "summary": "Add a call handling setting"
   }
  },
  "/phone/extension/{extensionId}/line_keys": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Line Keys"
    ],
    "description": "Use this API to get the Zoom Phone [line key settings](https://support.zoom.us/hc/en-us/articles/360040587552) information.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin` or `phone:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "listLineKeySetting",
    "summary": "Get line key position and settings information"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Line Keys"
    ],
    "description": "Use this API to batch update the Zoom Phone [line key settings](https://support.zoom.us/hc/en-us/articles/360040587552) information.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin` or `phone:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "BatchUpdateLineKeySetting",
    "summary": "Batch update line key position and settings information"
   }
  },
  "/phone/extension/{extensionId}/line_keys/{lineKeyId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Line Keys"
    ],
    "description": "Use this API to delete the Zoom Phone [line key settings](https://support.zoom.us/hc/en-us/articles/360040587552) information.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin` or `phone:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "DeleteLineKey",
    "summary": "Delete a line key setting."
   }
  },
  "/phone/external_contacts": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "External Contacts"
    ],
    "description": "Lists the external contacts.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "listExternalContacts",
    "summary": "List external contacts"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "External Contacts"
    ],
    "description": "Adds an external contact.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "addExternalContact",
    "summary": "Add an external contact"
   }
  },
  "/phone/external_contacts/{externalContactId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "External Contacts"
    ],
    "description": "Removes an external contact.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "deleteAExternalContact",
    "summary": "Delete an external contact"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "External Contacts"
    ],
    "description": "Gets an external contact's information.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions<br>",
    "operationId": "getAExternalContact",
    "summary": "Get external contact details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "External Contacts"
    ],
    "description": "Updates an external contact's information.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "updateExternalContact",
    "summary": "Update external contact"
   }
  },
  "/phone/locations": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Emergency Service Locations"
    ],
    "description": "Lists the emergency service locations.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "listLocations",
    "summary": "List emergency service locations"
   },
   "post": {
    "tags": [
     "Emergency Service Locations"
    ],
    "description": "Adds an emergency service location.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addLocation",
    "summary": "Add an emergency service location"
   }
  },
  "/phone/locations/{locationId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Emergency Service Locations"
    ],
    "description": "Removes an emergency location.\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "deleteLocation",
    "summary": "Delete an emergency location"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Emergency Service Locations"
    ],
    "description": "Returns an emergency service location's information.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "getLocation",
    "summary": "Get emergency service location details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Emergency Service Locations"
    ],
    "description": "Updates an emergency location's information.\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions",
    "operationId": "updateLocation",
    "summary": "Update emergency service location"
   }
  },
  "/phone/metrics/call_logs": {
   "get": {
    "tags": [
     "Dashboard"
    ],
    "description": " Lists the monthly call logs metrics. You can use query parameters to filter the response by date, site and MOS(Mean Opinion Score) of the call.The call logs that provide a record of all incoming and outgoing calls over Zoom Phone in an account. \n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:read:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "listCallLogsMetrics",
    "summary": "List call logs"
   }
  },
  "/phone/metrics/call_logs/{callId}/qos": {
   "get": {
    "tags": [
     "Dashboard"
    ],
    "description": "Gets the call quality of service (QoS) data for a call made or received by a Zoom phone user in the account. \n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license <br><br>\n**Scopes:** `phone:read:admin`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "getCallQoS",
    "summary": "Get call QoS"
   }
  },
  "/phone/metrics/call_logs/{call_id}": {
   "get": {
    "tags": [
     "Dashboard"
    ],
    "description": "Lists call log details of a specific call. The call logs provide a record of all incoming and outgoing calls over Zoom Phone in an account. \n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light",
    "operationId": "getCallLogMetricsDetails",
    "summary": "Get call details from call log"
   }
  },
  "/phone/metrics/location_tracking": {
   "get": {
    "tags": [
     "Dashboard"
    ],
    "description": "Lists the tracked locations. \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n* Account owner or admin permissions\n\n**Scope:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listTrackedLocations",
    "summary": "List tracked locations"
   }
  },
  "/phone/monitoring_groups": {
   "get": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to return an account's [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711) list.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "listMonitoringGroup",
    "summary": "Get a list of monitoring groups on an account"
   },
   "post": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to create a [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711).\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "createMonitoringGroup",
    "summary": "Create a monitoring group"
   }
  },
  "/phone/monitoring_groups/{monitoringGroupId}": {
   "delete": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to delete a [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711).\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "deleteMonitoringGroup",
    "summary": "Delete a monitoring group"
   },
   "get": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to return a [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711) for the specified ID.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "getMonitoringGroupById",
    "summary": "Get monitoring group by ID"
   },
   "patch": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to update a [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711).\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "updateMonitoringGroup",
    "summary": "Update a monitoring group"
   }
  },
  "/phone/monitoring_groups/{monitoringGroupId}/monitor_members": {
   "delete": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to remove all monitor or monitored members from a [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711).\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "removeMembers",
    "summary": "Remove all monitors or monitored members from a monitoring group"
   },
   "get": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to return members list of a [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711).\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "listMembers",
    "summary": "Get members of a monitoring group"
   },
   "post": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to add members to a [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711).\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "addMembers",
    "summary": "Add members to a monitoring group"
   }
  },
  "/phone/monitoring_groups/{monitoringGroupId}/monitor_members/{memberExtensionId}": {
   "delete": {
    "tags": [
     "Monitoring Groups"
    ],
    "description": "Use this API to remove a member from a [Monitoring Group](https://support.zoom.us/hc/en-us/articles/360044804711).\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "removeMember",
    "summary": "Remove a member from a monitoring group"
   }
  },
  "/phone/outbound_caller_id/customized_numbers": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to retrieve phone numbers that can be used as the `account-level` customized outbound caller ID. Note that when multiple sites policy is enabled, users cannot manage the `account-level` configuration. The system will throw an exception. \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:read:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "listCustomizeOutboundCallerNumbers",
    "summary": "List an account's customized outbound caller ID phone numbers"
   },
   "post": {
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to add the `account-level` customized outbound caller ID phone numbers. Note that when multiple sites policy is enabled, users cannot manage the `account-level` configuration. The system will throw an exception.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addOutboundCallerNumbers",
    "summary": "Add phone numbers for an account's customized outbound caller ID"
   },
   "delete": {
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to delete the `account-level` customized outbound caller ID phone numbers. Note that when multiple sites policy is enabled, users cannot manage the `account-level` configuration. The system will throw an exception.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteOutboundCallerNumbers",
    "summary": "Delete phone numbers for an account's customized outbound caller ID"
   }
  },
  "/phone/numbers": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to list all Zoom Phone numbers in a Zoom account.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "listAccountPhoneNumbers",
    "summary": "List phone numbers"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to delete unassigned [phone numbers](https://support.zoom.us/hc/en-us/articles/360020808292-Managing-Phone-Numbers#h_38ba8b01-26e3-4b1b-a9b5-0717c00a7ca6). Up to 20 phone numbers can be removed in a single request.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license \n* The user must have been previously assigned a Zoom Phone number\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refe[...]",
    "operationId": "deleteUnassignedPhoneNumbers",
    "summary": "Delete unassigned phone numbers"
   }
  },
  "/phone/numbers/{numberId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to get information about an account's Zoom Phone number.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom phone license",
    "operationId": "getPhoneNumberDetails",
    "summary": "Get a phone number"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to update a Zoom Phone number's information.\n\n**Scopes:** `phone:write`, `phone:write:admin`, `phone:master`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Paid account",
    "operationId": "updatePhoneNumberDetails",
    "summary": "Update a phone number"
   }
  },
  "/phone/numbers/sites/{siteId}": {
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to update a site's unassigned [phone numbers](https://support.zoom.us/hc/en-us/articles/360020808292-Managing-Phone-Numbers#h_38ba8b01-26e3-4b1b-a9b5-0717c00a7ca6). Up to 20 phone numbers can be updated in a single request. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "updateSiteForUnassignedPhoneNumbers",
    "summary": "Update a site's unassigned phone numbers"
   }
  },
  "/phone/peering/numbers": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Provider Exchange"
    ],
    "description": "Removes phone numbers added to Zoom through the Provider Exchange.\n\n**Note**: Phone peering API and events are for partners who have completed the MoU to peer with Zoom. To become a peering provider/ carrier, submit your [request](https://docs.google.com/forms/d/e/1FAIpQLSewkY6ixVyKVNkWC-vgmejC16gigxsJWXji3dWzE3XlWtjsgg/viewform).\n\n**Scopes**: `phone_peering:write:admin`, `phone_peering:master`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-l[...]",
    "operationId": "deletePeeringPhoneNumbers",
    "summary": "Remove peering phone numbers"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Provider Exchange"
    ],
    "description": "Returns phone numbers to Zoom through the Provider Exchange.\n\n**Note**: Phone peering API and events are for partners who have completed the MoU to peer with Zoom. To become a peering provider/ carrier, submit your [request](https://docs.google.com/forms/d/e/1FAIpQLSewkY6ixVyKVNkWC-vgmejC16gigxsJWXji3dWzE3XlWtjsgg/viewform).\n\n**Scopes:** `phone_peering:read:admin`, `phone_peering:master`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#r[...]",
    "operationId": "listPeeringPhoneNumbers",
    "summary": "List peering phone numbers"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Provider Exchange"
    ],
    "description": "Updates phone numbers to Zoom through the Provider Exchange.\n\n**Note**: Phone peering API and events are for partners that have completed the MoU to peer with Zoom. To become a peering provider/ carrier, submit your [request](https://docs.google.com/forms/d/e/1FAIpQLSewkY6ixVyKVNkWC-vgmejC16gigxsJWXji3dWzE3XlWtjsgg/viewform).\n\n**Scopes:** `phone_peering:write:admin`, `phone_peering:master`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits[...]",
    "operationId": "updatePeeringPhoneNumbers",
    "summary": "Update peering phone numbers"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Provider Exchange"
    ],
    "description": "Adds phone numbers to Zoom through the Provider Exchange.\n\n**Note**: Phone peering API and events are for partners who have completed the MoU to peer with Zoom. To become a peering provider/ carrier, submit your [request](https://docs.google.com/forms/d/e/1FAIpQLSewkY6ixVyKVNkWC-vgmejC16gigxsJWXji3dWzE3XlWtjsgg/viewform).\n\n**Scopes:** `phone_peering:write:admin`, `phone_peering:master`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rat[...]",
    "operationId": "addPeeringPhoneNumbers",
    "summary": "Add peering phone numbers"
   }
  },
  "/phone/carrier_peering/numbers": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Provider Exchange"
    ],
    "description": "Returns phone numbers pushed by the carrier to different customers.\nTo become a peering provider/ carrier, submit your [request](https://docs.google.com/forms/d/e/1FAIpQLSewkY6ixVyKVNkWC-vgmejC16gigxsJWXji3dWzE3XlWtjsgg/viewform).\n\n**Scopes:** `phone_peering:read:admin`, `phone_peering:master`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phon[...]",
    "operationId": "listCarrierPeeringPhoneNumbers",
    "summary": "List carrier peering phone numbers."
   }
  },
  "/phone/ported_numbers/orders": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Settings"
    ],
    "description": "Use this API to list ported numbers in a Zoom account.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "listPortedNumbers",
    "summary": "List ported numbers"
   }
  },
  "/phone/ported_numbers/orders/{orderId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Settings"
    ],
    "description": "Use this API to get details on the ported numbers by specifying `order_id`.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom phone license",
    "operationId": "getPortedNumbersDetails",
    "summary": "Get ported number details"
   }
  },
  "/phone/recording_transcript/download/{recordingId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Recordings"
    ],
    "description": "Downloads the phone recording transcript. \n\n**Prerequisites:**\n\n* A Business or Enterprise account\n* A Zoom Phone license\n\n**Scopes:** `phone:read`, `phone:read:admin`, `phone_recording:read`, `phone_recording:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n\n\n",
    "operationId": "phoneDownloadRecordingTranscript",
    "summary": "Download a phone recording transcript"
   }
  },
  "/phone/recordings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Recordings"
    ],
    "description": "Lists an account's [call recordings](https://support.zoom.us/hc/en-us/articles/360038521091-Accessing-and-sharing-call-recordings).\n\n**Prerequisites:**\n* A Pro or higher account plan \n* A Zoom Phone license \n* Account owner or admin privileges**Scopes:** `phone:read:admin`, `phone_recording:read:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` ",
    "operationId": "getPhoneRecordings",
    "summary": "Get call recordings"
   }
  },
  "/phone/recordings/{recordingId}": {
   "delete": {
    "tags": [
     "Recordings"
    ],
    "description": "Deletes a call recording.\n\n**Scopes:** `phone:write`, `phone:write:admin`, `phone_recording:write`, `phone_recording:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* User must belong to a Business or Enterprise account \n* User must have a Zoom Phone license",
    "operationId": "deleteCallRecording",
    "summary": "Delete a call recording"
   }
  },
  "/phone/reports/operationlogs": {
   "get": {
    "tags": [
     "Reports"
    ],
    "description": "The **Phone System operation logs report** allows account owners and admins to view monthly Zoom phone related admin operation details. \n\nUse this API to retrieve the **Phone System Operation Logs Report**. Account owners and admins can also access this information by logging into their Zoom accounts and navigating to [Phone System Operation Logs](https://zoom.us/pbx/page/report/operations#/report/operation-logs).<br><br> **Scopes:** `phone:read:admin`<br> **[Rate Limit Lab[...]",
    "operationId": "getPSOperationLogs",
    "summary": "Get operation logs report"
   }
  },
  "/phone/rooms": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to retrieve a list of [Zoom Rooms](https://support.zoom.us/hc/en-us/articles/360025153711) under the account that has the Zoom Phone license assigned.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "listZoomRooms",
    "summary": "List Zoom Rooms under Zoom Phone license"
   },
   "post": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to associate a [Zoom Room](https://support.zoom.us/hc/en-us/articles/360025153711#h_70c74c57-50d6-406b-a4fa-2f33d4bebdbc) with a Zoom Phone license. \n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "addZoomRoom",
    "summary": "Add a Zoom Room to a Zoom Phone"
   }
  },
  "/phone/rooms/unassigned": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to retrieve [Zoom Rooms](https://support.zoom.us/hc/en-us/articles/360025153711) that are not assigned a Zoom Phone.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "listUnassignedZoomRooms",
    "summary": "List Zoom Rooms without Zoom Phone assignment"
   }
  },
  "/phone/rooms/{roomId}": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to get a specific [Zoom Room](https://support.zoom.us/hc/en-us/articles/360025153711) in an account that has the Zoom Phone license assigned.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "getZoomRoom",
    "summary": "Get a Zoom Room under Zoom Phone license"
   },
   "patch": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to update a [Zoom Room](https://support.zoom.us/hc/en-us/articles/360025153711) in an account that has the Zoom Phone license assigned.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "updateZoomRoom",
    "summary": "Update a Zoom Room under Zoom Phone license"
   },
   "delete": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to remove [Zoom Room](https://support.zoom.us/hc/en-us/articles/360025153711#h_140e30ba-5a88-40b9-b799-16883fa0a037) from a Zoom Phone account.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "RemoveZoomRoom",
    "summary": "Remove a Zoom Room from a ZP account"
   }
  },
  "/phone/rooms/{roomId}/calling_plans": {
   "post": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to assign [calling plans](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans) to a [Zoom Room](https://support.zoom.us/hc/en-us/articles/360025153711#h_70c74c57-50d6-406b-a4fa-2f33d4bebdbc). Up to 200 numbers at a time.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n[...]",
    "operationId": "assignCallingPlanToRoom",
    "summary": "Assign calling plans to a Zoom Room"
   }
  },
  "/phone/rooms/{roomId}/calling_plans/{type}": {
   "delete": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to unassign a [calling plan](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans) from a [Zoom Room](https://support.zoom.us/hc/en-us/articles/360025153711#h_140e30ba-5a88-40b9-b799-16883fa0a037).\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "unassignCallingPlanFromRoom",
    "summary": "Remove a calling plan from a Zoom Room"
   }
  },
  "/phone/rooms/{roomId}/phone_numbers": {
   "post": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to [assign phone numbers to a Zoom Room](https://support.zoom.us/hc/en-us/articles/360025153711). Up to 200 numbers at a time.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "assignPhoneNumberToZoomRoom",
    "summary": "Assign phone numbers to a Zoom Room"
   }
  },
  "/phone/rooms/{roomId}/phone_numbers/{phoneNumberId}": {
   "delete": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to unassign a [phone number](https://support.zoom.us/hc/en-us/articles/360020808292-Managing-Phone-Numbers#h_38ba8b01-26e3-4b1b-a9b5-0717c00a7ca6) from a [Zoom Room](https://support.zoom.us/hc/en-us/articles/360025153711#h_140e30ba-5a88-40b9-b799-16883fa0a037).\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* [...]",
    "operationId": "UnassignPhoneNumberFromZoomRoom",
    "summary": "Remove a phone number from a Zoom Room"
   }
  },
  "/phone/routing_rules": {
   "get": {
    "tags": [
     "Directory Backup Routing Rules"
    ],
    "description": "Use this API to return a list of directory backup routing rules. The directory backup routing rules are a series of predefined Regular Expressions. These rules are used to route outgoing calls. If a dialed number does not match a Zoom Phone user, and does not match a defined External Contact, these rules are tested next. If a dialed number does not match any rules, the call will be routed via the PSTN. \n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketp[...]",
    "operationId": "listRoutingRule",
    "summary": "List directory backup routing rules"
   },
   "post": {
    "tags": [
     "Directory Backup Routing Rules"
    ],
    "description": "Use this API to create a directory backup routing rule. The directory backup routing rules are a series of predefined Regular Expressions. These rules are used to route outgoing calls. If a dialed number does not match a Zoom Phone user, and does not match a defined External Contact, these rules are tested next. If a dialed number does not match any rules, the call will be routed via the PSTN.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom[...]",
    "operationId": "addRoutingRule",
    "summary": "Add directory backup routing rule"
   }
  },
  "/phone/routing_rules/{routingRuleId}": {
   "delete": {
    "tags": [
     "Directory Backup Routing Rules"
    ],
    "description": "Use this API to delete directory backup routing rule. The directory backup routing rules are a series of predefined Regular Expressions. These rules are used to route outgoing calls. If a dialed number does not match a Zoom Phone user, and does not match a defined External Contact, these rules are tested next. If a dialed number does not match any rules, the call will be routed via the PSTN.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.u[...]",
    "operationId": "deleteRoutingRule",
    "summary": "Delete directory backup routing rule"
   },
   "get": {
    "tags": [
     "Directory Backup Routing Rules"
    ],
    "description": "Use this API to get directory backup routing rule. The directory backup routing rules are a series of predefined Regular Expressions. These rules are used to route outgoing calls. If a dialed number does not match a Zoom Phone user, and does not match a defined External Contact, these rules are tested next. If a dialed number does not match any rules, the call will be routed via the PSTN.\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/do[...]",
    "operationId": "getRoutingRule",
    "summary": "Get directory backup routing rule"
   },
   "patch": {
    "tags": [
     "Directory Backup Routing Rules"
    ],
    "description": "Use this API to update directory backup routing rule. The directory backup routing rules are a series of predefined Regular Expressions. These rules are used to route outgoing calls. If a dialed number does not match a Zoom Phone user, and does not match a defined External Contact, these rules are tested next. If a dialed number does not match any rules, the call will be routed via the PSTN.\n\n**Scopes:** `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.u[...]",
    "operationId": "updateRoutingRule",
    "summary": "Update directory backup routing rule"
   }
  },
  "/phone/setting_templates": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Setting Templates"
    ],
    "description": "Gets a list of all the created phone template settings.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "listSettingTemplates",
    "summary": "List setting templates"
   },
   "post": {
    "tags": [
     "Setting Templates"
    ],
    "description": "Creates a Zoom Phone setting template for an account. After creating a phone template, the defined settings will become the default settings for an account.\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or enterprise Zoom account \n* A Zoom Phone license",
    "operationId": "addSettingTemplate",
    "summary": "Add a setting template"
   }
  },
  "/phone/setting_templates/{templateId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Setting Templates"
    ],
    "description": "Returns information about an account's phone template.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "getSettingTemplate",
    "summary": "Get setting template details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Setting Templates"
    ],
    "description": "Updates or modifies a phone template's settings.\n\n**Scopes:** `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "updateSettingTemplate",
    "summary": "Update a setting template"
   }
  },
  "/phone/settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Settings"
    ],
    "description": "Use this API to return an account's settings.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "phoneSetting",
    "summary": "Get phone account settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Settings"
    ],
    "description": "Account owners can use this API to update Zoom Phone [account settings](https://support.zoom.us/hc/en-us/articles/360025846692).\n\n**Scopes:** `phone:write:admin`\n\n**Prerequisites:** \n* A Business or Enterprise account",
    "operationId": "updatePhoneSettings",
    "summary": "Update phone account settings"
   }
  },
  "/phone/shared_line_appearances": {
   "get": {
    "tags": [
     "Shared Line Appearance"
    ],
    "description": "Use this API to list [shared line appearance](https://support.zoom.us/hc/en-us/articles/4406753208461-Enabling-or-disabling-shared-lines-privacy-mode) instances.\n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license \n* Account owner or admin privileges  \n\n**Scopes:** `phone:read:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listSharedLineAppearances",
    "summary": "List shared line appearances"
   }
  },
  "/phone/shared_line_groups": {
   "get": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "A [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) allows Zoom Phone admins to share a phone number and extension with a group of phone users or common area phones. This gives members of the shared line group access to the group's direct phone number and voicemail. Use this API to list all the Shared Line Groups.\n\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges  \n\n\n**Scopes:** `phone:[...]",
    "operationId": "listSharedLineGroups",
    "summary": "List shared line groups"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Shared Line Group"
    ],
    "description": "A [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) allows Zoom Phone admins to share a phone number and extension with a group of phone users or common area phones. This gives members of the shared line group access to the group's direct phone number and voicemail. Use this API to create a shared line group.\n\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:ad[...]",
    "operationId": "createASharedLineGroup",
    "summary": "Create a shared line group"
   }
  },
  "/phone/shared_line_groups/{sharedLineGroupId}": {
   "delete": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "A [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) allows Zoom Phone admins to share a phone number and extension with a group of phone users or common area phones. Use this API to delete a Shared Line Group. \n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:admin`\n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits[...]",
    "operationId": "deleteASharedLineGroup",
    "summary": "Delete a shared line group"
   },
   "get": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "A [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) allows Zoom Phone admins to share a phone number and extension with a group of phone users or common area phones. This gives members of the shared line group access to the group's direct phone number and voicemail. Use this API to list all the Shared Line Groups.\n\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:rea[...]",
    "operationId": "getASharedLineGroup",
    "summary": "Get a shared line group"
   },
   "patch": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "A [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) allows Zoom Phone admins to share a phone number and extension with a group of phone users or common area phones. This gives members of the shared line group access to the group's direct phone number and voicemail. Use this API to update information of a Shared Line Group. \n\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:**[...]",
    "operationId": "updateASharedLineGroup",
    "summary": "Update a shared line group"
   }
  },
  "/phone/shared_line_groups/{sharedLineGroupId}/members": {
   "delete": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "Members of the [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) have access to the group's phone number and voicemail. Use this API to unassign **all** existing members from a Shared Line Group.\n\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* A valid Shared Line Group\n* Account owner or admin privileges\n\n**Scopes:** `phone:write:admin`\n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-lim[...]",
    "operationId": "deleteMembersOfSLG",
    "summary": "Unassign members from a shared line group"
   },
   "post": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "A [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) allows Zoom Phone admins to share a phone number and extension with a group of phone users or common area phones. This gives members of the shared line group access to the group's direct phone number and voicemail. Use this API to [add members](https://support.zoom.us/hc/en-us/articles/360038850792-Setting-up-shared-line-groups#h_7cb42370-48f6-4a8f-84f4-c6eee4d9f0ca) to a Shared Line Group. Note tha[...]",
    "operationId": "addMembersToSharedLineGroup",
    "summary": "Add members to a shared line group"
   }
  },
  "/phone/shared_line_groups/{sharedLineGroupId}/members/{memberId}": {
   "delete": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "Members of the [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) have access to the group's phone number and voicemail. Use this API to unassign **a specific member** from a Shared Line Group.\n\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* A valid Shared Line Group\n* Account owner or admin privileges\n\n**Scopes:** `phone:write:admin`\n\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits[...]",
    "operationId": "deleteAMemberSLG",
    "summary": "Unassign a member from a shared line group"
   }
  },
  "/phone/shared_line_groups/{sharedLineGroupId}/phone_numbers": {
   "delete": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "Use this API to unassign all the phone numbers that have been assigned to the [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792-Setting-up-shared-line-groups).\n\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* A valid Shared Line Group\n* Account owner or admin privileges\n\n**Scopes:** `phone:write:admin`\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deletePhoneNumbersSLG",
    "summary": "Unassign all phone numbers",
    "x-private": false
   },
   "post": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "Use this API to assign phone numbers to a shared line groups. These direct phone numbers will be shared among members of the [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792-Setting-up-shared-line-groups).\n\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* A valid Shared Line Group\n* Account owner or admin privileges\n\n**Scopes:** `phone:write:admin`\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/ra[...]",
    "operationId": "assignPhoneNumbersSLG",
    "summary": "Assign phone numbers"
   }
  },
  "/phone/shared_line_groups/{sharedLineGroupId}/phone_numbers/{phoneNumberId}": {
   "delete": {
    "tags": [
     "Shared Line Group"
    ],
    "description": "Use this API to unassign a specific phone number that was assigned to the [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792-Setting-up-shared-line-groups).\n**Prerequisites:** \n\n* Pro or higher account with Zoom Phone license.\n* A valid Shared Line Group\n* Account owner or admin privileges\n\n**Scopes:** `phone:write:admin`\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteAPhoneNumberSLG",
    "summary": "Unassign a phone number"
   }
  },
  "/phone/shared_line_groups/{sharedLineGroupId}/policy/{policyType}": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Shared Line Group"
    ],
    "description": "Use this API to add the policy sub-setting for a specific [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) according to the `policyType`. For example, you can use this API to set up shared access members. \n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `[...]",
    "operationId": "addSLGPolicySubSetting",
    "summary": "Add a policy setting to a shared line group"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Shared Line Group"
    ],
    "description": "Use this API to update the policy sub-setting for a specific [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) according to the `policyType`. For example, you can use this API to update shared access members. \n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):*[...]",
    "operationId": "updateSLGPolicySubSetting",
    "summary": "Update an SLG policy setting"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Shared Line Group"
    ],
    "description": "Use this API to remove the policy sub-setting for a specific [shared line group](https://support.zoom.us/hc/en-us/articles/360038850792) according to the `policyType`. For example, you can use this API to remove shared access members. \n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n**Scopes:** `phone:write:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):*[...]",
    "operationId": "removeSLGPolicySubSetting",
    "summary": "Delete an SLG policy setting"
   }
  },
  "/phone/sip_groups": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Settings"
    ],
    "description": "Use this API to list SIP (Session Initiation Protocol) groups.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions",
    "operationId": "listSipGroups",
    "summary": "List SIP groups"
   }
  },
  "/phone/sip_trunk/trunks": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Settings"
    ],
    "description": "Use this API to return a list of an account's assigned [BYOC (Bring Your Own Carrier) SIP (Session Initiation Protocol) trunks](https://zoom.us/docs/doc/Zoom-Bring%20Your%20Own%20Carrier.pdf).\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account",
    "operationId": "listBYOCSIPTrunk",
    "summary": "List BYOC SIP trunks"
   }
  },
  "/phone/sites": {
   "get": {
    "tags": [
     "Sites"
    ],
    "description": "Sites allow you to organize Zoom Phone users in your organization. Use this API to list all the [sites](https://support.zoom.us/hc/en-us/articles/360020809672) that have been created for an account.<br>\n**Prerequisites:**<br>\n* Multiple Sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).\n* Pro or a higher account with Zoom Phone enabled.\n\n\n**Scope:** `phone:read:admin`<br> \n **[[...]",
    "operationId": "listPhoneSites",
    "summary": "List phone sites"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Sites"
    ],
    "description": "Use this API to create a [site](https://support.zoom.us/hc/en-us/articles/360020809672). It allows you to organize the Zoom Phone users in your organization.\n\n**Prerequisites:**\n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15). \n* Pro or a higher account with Zoom Phone enabled.\n\n**Scope:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/doc[...]",
    "operationId": "createPhoneSite",
    "summary": "Create a phone site"
   }
  },
  "/phone/sites/{siteId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Sites"
    ],
    "description": " Use this API to delete a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672) in a Zoom account. To delete a site, in the query parameter, you must provide the site ID of another site where the assets of current site (users, numbers and phones) can be transferred to.  You cannot use this API to delete the main site.\n\n**Prerequisites:** \n\n* Account must have a Pro or a higher plan with Zoom Phone license. \n* [Multiple sites](https://support.zoom.us/hc/[...]",
    "operationId": "deletePhoneSite",
    "summary": "Delete a phone site"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Sites"
    ],
    "description": "Sites allow you to organize Zoom Phone users in your organization. Use this API to get information on a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672).\n\n**Prerequisites:** \n* Account must have a Pro or a higher plan with Zoom Phone license.\n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).\n\n**Scope:** `phone:read:admin`\n \n **[Rate Limit Lab[...]",
    "operationId": "getASite",
    "summary": "Get phone site details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Sites"
    ],
    "description": "Allows you to organize Zoom Phone users in your organization. Use this API to update information about a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672).\n\n\n**Prerequisites:** \n\n* Account must have a Pro or a higher plan with Zoom Phone license.\n* **Scope:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "updateSiteDetails",
    "summary": "Update phone site details"
   }
  },
  "/phone/sites/{siteId}/settings/{settingType}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Sites"
    ],
    "description": "Sites allow you to organize Zoom Phone users in your organization. Use this API to get site setting about a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672) according to the setting type.\n\n**Prerequisites:** \n\n* Account must have a Pro or a higher plan with Zoom Phone license.\n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).\n\n**Scope:** `phon[...]",
    "operationId": "getSiteSettingForType",
    "summary": "Get a phone site setting"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Sites"
    ],
    "description": "Sites allow you to organize Zoom Phone users in your organization. Use this API to update the site setting of a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672) according to the setting type.\n\n**Prerequisites:** \n* Account must have a Pro or a higher plan with Zoom Phone license.\n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).\n\n**Scope:** `ph[...]",
    "operationId": "updateSiteSetting",
    "summary": "Update the site setting"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Sites"
    ],
    "description": "Sites allow you to organize Zoom Phone users in your organization. Use this API to add a site setting to a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672) according to the setting type.\n\n**Prerequisites:** \n* Account must have a Pro or a higher plan with Zoom Phone license.\n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).\n\n**Scope:** `phone:w[...]",
    "operationId": "addSiteSetting",
    "summary": "Add a site setting"
   },
   "delete": {
    "tags": [
     "Sites"
    ],
    "description": "Sites allow you to organize Zoom Phone users in your organization. Use this API to delete the site setting of a specific [site](https://support.zoom.us/hc/en-us/articles/360020809672).\n\n**Prerequisites:** \n* Account must have a Pro or a higher plan with Zoom Phone license.\n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15).\n\n**Scope:** `phone:write:admin`\n \n **[Rate [...]",
    "operationId": "deleteSiteSetting",
    "summary": "Delete a site setting"
   }
  },
  "/phone/sites/{siteId}/outbound_caller_id/customized_numbers": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Sites"
    ],
    "description": "Use this API to retrieve phone numbers that can be used as the `site-level` customized outbound caller ID. \n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15). \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:read:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits)[...]",
    "operationId": "listSiteCustomizeOutboundCallerNumbers",
    "summary": "List customized outbound caller ID phone numbers"
   },
   "post": {
    "tags": [
     "Sites"
    ],
    "description": "Use this API to add the `site-level` customized outbound caller ID phone numbers. \n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15). \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addSiteOutboundCallerNumbers",
    "summary": "Add customized outbound caller ID phone numbers"
   },
   "delete": {
    "tags": [
     "Sites"
    ],
    "description": "Use this API to remove the `site-level` customized outbound caller ID phone numbers. \n* Multiple sites must be [enabled](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-Multiple-Sites#h_05c88e35-1593-491f-b1a8-b7139a75dc15). \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteSiteOutboundCallerNumbers",
    "summary": "Remove customized outbound caller ID phone numbers"
   }
  },
  "/phone/sms/sessions": {
   "get": {
    "tags": [
     "SMS"
    ],
    "description": "Get details about SMS sessions for an account.\n\n**Scopes:** `phone_sms:read:admin`, `phone_sms:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites**\n* Paid account\n* User-enabled Zoom phone\n\n",
    "operationId": "accountSmsSession",
    "summary": "Get account's SMS sessions",
    "x-private": false
   }
  },
  "/phone/sms/sessions/{sessionId}": {
   "get": {
    "tags": [
     "SMS"
    ],
    "description": "Get details about an SMS session.\n\n**Scopes:** `phone_sms:read`, `phone_sms:read:admin`, `phone_sms:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites**\n* Paid account\n* User-enabled Zoom phone\n\n",
    "operationId": "smsSessionDetails",
    "summary": "Get SMS session details",
    "x-private": false
   }
  },
  "/phone/sms/sessions/{sessionId}/sync": {
   "get": {
    "tags": [
     "SMS"
    ],
    "description": "Use this API to sync SMS messages in a session. \n\n**Scopes:** `phone_sms:read`, `phone_sms:read:admin`, `phone_sms:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites**\n* Paid account\n* User-enabled Zoom phone\n\n",
    "operationId": "smsSessionSync",
    "summary": "Sync SMS by session ID"
   }
  },
  "/phone/sms/sessions/{sessionId}/messages/{messageId}": {
   "get": {
    "tags": [
     "SMS"
    ],
    "description": "Get details about a specific message in an SMS session.\n\n**Scopes:** `phone_sms:read`, `phone_sms:read:admin`, `phone_sms:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`\n\n**Prerequisites**\n* Paid account\n* User-enabled Zoom phone\n\n",
    "operationId": "smsByMessageId",
    "summary": "Get SMS by message ID",
    "x-private": false
   }
  },
  "/phone/users": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Returns a list of all of an account's users who are assigned a Zoom Phone license.\n\n**Scopes:** `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license",
    "operationId": "listPhoneUsers",
    "summary": "List phone users"
   }
  },
  "/phone/users/batch": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Adds phone users in batch. You can add up to 10 users at a time.\n\n**Prerequisites:**\n* The users must be active in your [Zoom account](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods#tag/Users/operation/users). \n* Pro or higher account plan with Zoom phone license\n* Account owner or admin permissions\n\n**Scope:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "batchAddUsers",
    "summary": "Batch add users"
   }
  },
  "/phone/users/{userId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Returns a user's [Zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) profile. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:read`, `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n * A Busin[...]",
    "operationId": "phoneUser",
    "summary": "Get a user's profile"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Updates a user's [Zoom Phone](https://support.zoom.us/hc/en-us/categories/360001370051-Zoom-Phone) profile. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nTo add, update or remove the shared access members for voicemail and call recordings, use the [Add](https://marketplace.zoom.us/docs/api-reference/phone/methods#tag/Users/operation/addUserSetting)/[Update](https://mar[...]",
    "operationId": "updateUserProfile",
    "summary": "Update a user's profile"
   }
  },
  "/phone/users/{userId}/audios": {
   "get": {
    "tags": [
     "Audio Library"
    ],
    "description": "Gets the audio items.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:read`,`phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "ListAudioItems",
    "summary": "List audio items"
   },
   "post": {
    "tags": [
     "Audio Library"
    ],
    "description": "Adds an audio item for [text-to-speech conversion](https://support.zoom.us/hc/en-us/articles/4402414203533-Using-the-audio-library-to-customize-audio#h_01F8B0D2ZJBKEDH10DFZ7J2CM7).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:write`,`phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
    "operationId": "AddAnAudio",
    "summary": "Add an audio item for text-to-speech conversion"
   }
  },
  "/phone/users/{userId}/audios/batch": {
   "post": {
    "tags": [
     "Audio Library"
    ],
    "description": "Adds audio items. You can only upload voice files at this time.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:write`,`phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`\n\n\n**Size and quantity limits for audio attachments:**\n* Up to 5 attachments\n* Each file size should be no more than 1MB",
    "operationId": "AddAudioItem",
    "summary": "Add audio items"
   }
  },
  "/phone/users/{userId}/call_logs": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Logs"
    ],
    "description": "Gets a user's [Zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) call logs. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:read`, `phone:read:admin`, `phone_call_log:read`, `phone_call_log:read:admin`\n\n[...]",
    "operationId": "phoneUserCallLogs",
    "summary": "Get user's call logs"
   }
  },
  "/phone/users/{userId}/call_logs/sync": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Call Logs"
    ],
    "description": "Syncs a user's [Zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) call logs. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:read`, `phone:read:admin`, `phone_call_log:read`, `phone_call_log:read:admin`\n\[...]",
    "operationId": "syncUserCallLogs",
    "summary": "Sync user's call logs"
   }
  },
  "/phone/users/{userId}/call_logs/{callLogId}": {
   "delete": {
    "tags": [
     "Call Logs"
    ],
    "description": "Deletes a user's [call log](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-and-identifying-logs). For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites:** \n* User must belong to a Business or Enterprise account \n* User must have a Zoom Phone license\n\n**Scopes:** `phone:write`, `phone:write:admin`, `phone_call_log:write`, `phone_call_log:writ[...]",
    "operationId": "deleteCallLog",
    "summary": "Delete a user's call log"
   }
  },
  "/phone/users/{userId}/call_logs/{id}/voice_mail": {
   "get": {
    "tags": [
     "Voicemails"
    ],
    "description": "Use this API to return detailed information on a voicemail associated with a call log ID. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:read`, `phone:read:admin`, `phone_voicemail:read`, `phone_voicemail:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* User [...]",
    "operationId": "getVoicemailDetailsByCallIdOrCallLogId",
    "summary": "Get user voicemail details from a call log"
   }
  },
  "/phone/users/{userId}/calling_plans": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Assigns a [calling plan](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans) to a [Zoom Phone](https://support.zoom.us/hc/en-us/categories/360001370051-Zoom-Phone) user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:write`, `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refer[...]",
    "operationId": "assignCallingPlan",
    "summary": "Assign calling plan to a user"
   },
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Switches [calling plans](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans) of a [Zoom Phone](https://support.zoom.us/hc/en-us/categories/360001370051-Zoom-Phone) user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:write:a[...]",
    "operationId": "updateCallingPlan",
    "summary": "Update user's calling plan"
   }
  },
  "/phone/users/{userId}/calling_plans/{type}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Unassigns a a [Zoom Phone](https://support.zoom.us/hc/en-us/categories/360001370051) user's [calling plan](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans). For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:write`, `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-[...]",
    "operationId": "unassignCallingPlan",
    "summary": "Unassign user's calling plan"
   }
  },
  "/phone/users/{userId}/phone_numbers": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to assign a [phone number](https://support.zoom.us/hc/en-us/articles/360020808292-Managing-Phone-Numbers) to a user who has already enabled Zoom Phone.\n\n**Scopes:** `phone:write`, `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "assignPhoneNumber",
    "summary": "Assign a phone number to a user"
   }
  },
  "/phone/users/{userId}/phone_numbers/{phoneNumberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Numbers"
    ],
    "description": "Use this API to unassign Zoom Phone user's [phone number](https://support.zoom.us/hc/en-us/articles/360020808292-Managing-Phone-Numbers#h_38ba8b01-26e3-4b1b-a9b5-0717c00a7ca6).\n\nAfter assigning a phone number, you can remove it if you do not want it to be assigned to anyone.\n\n**Scopes:** `phone:write`, `phone:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enter[...]",
    "operationId": "UnassignPhoneNumber",
    "summary": "Unassign a phone number"
   }
  },
  "/phone/users/{userId}/recordings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Recordings"
    ],
    "description": "Gets a user's [Zoom Phone recordings](https://support.zoom.us/hc/en-us/articles/360021336671-Viewing-Call-History-and-Recordings). For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:read`, `phone:read:admin`, `phone_recording:read`, `phone_recording:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits)[...]",
    "operationId": "phoneUserRecordings",
    "summary": "Get user's recordings"
   }
  },
  "/phone/users/{userId}/settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Gets the Zoom Phone [profile settings](https://support.zoom.us/hc/en-us/articles/360021325712-Configuring-Settings) of a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:read`, `phone:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Enterpri[...]",
    "operationId": "phoneUserSettings",
    "summary": "Get a user's profile settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Updates the Zoom Phone [profile settings](https://support.zoom.us/hc/en-us/articles/360021325712-Configuring-Settings) of a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:write`, `phone:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Business or Ent[...]",
    "operationId": "updateUserSettings",
    "summary": "Update a user's profile settings"
   }
  },
  "/phone/users/{userId}/settings/{settingType}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Removes the user setting according to the setting type, specifically for delegation, intercom and shared access for voicemail and call recordings. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nTo see the shared access settings in the Zoom web portal, go to **Admin > Phone System Management > Users & Rooms** . Click **Users** and select **User Policy**. Go to **Voicemai[...]",
    "operationId": "deleteUserSetting",
    "summary": "Delete a user's shared access setting"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Updates the user setting according to the setting type, specifically for delegation, intercom and shared access for voicemail and call recordings. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nTo see the shared access settings in the Zoom web portal, go to **Admin > Phone System Management > Users & Rooms** . Click **Users** and select **User Policy**. Go to **Voicemai[...]",
    "operationId": "updateUserSetting",
    "summary": "Update a user's shared access setting"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Adds the user setting according to the setting type, specifically for delegation, intercom and shared access for voicemail, and call recordings. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nTo see the shared access settings in the Zoom web portal, go to **Admin > Phone System Management > Users & Rooms** . Click **Users** and select **User Policy**. Go to **Voicemail,[...]",
    "operationId": "addUserSetting",
    "summary": "Add a user's shared access setting"
   }
  },
  "/phone/users/{userId}/outbound_caller_id/customized_numbers": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Retrieves phone numbers that can be the `user-level` customized outbound caller ID. \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:read:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "listUserCustomizeOutboundCallerNumbers",
    "summary": "List users' phone numbers for a customized outbound caller ID"
   },
   "post": {
    "tags": [
     "Users"
    ],
    "description": "Adds users' customized outbound caller ID phone numbers. \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addUserOutboundCallerNumbers",
    "summary": "Add phone numbers for users' customized outbound caller ID"
   },
   "delete": {
    "tags": [
     "Users"
    ],
    "description": "Removes the users' customized outbound caller ID phone numbers. \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n**Scope:** `phone:write:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteUserOutboundCallerNumbers",
    "summary": "Remove users' customized outbound caller ID phone numbers"
   }
  },
  "/phone/users/{userId}/sms/sessions": {
   "get": {
    "tags": [
     "SMS"
    ],
    "description": "Get details about SMS sessions for a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone_sms:read`, `phone_sms:read:admin`, `phone_sms:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`\n\n**Prerequisites:** \n* Paid account \n* User-enabled Zoom phone",
    "operationId": "userSmsSession",
    "summary": "Get user's SMS sessions",
    "x-private": false
   }
  },
  "/phone/users/{userId}/sms/sessions/sync": {
   "get": {
    "tags": [
     "SMS"
    ],
    "description": "Use this API to retrieve user's SMS sessions in descending order. Mirrors the ZP client behavior with the most recent on top.\n\n**Prerequisites:**\n* Paid account \n* User-enabled Zoom phone \n\n**Scopes:** `phone_sms:read`, `phone_sms:read:admin`, `phone_sms:master`\n\n**Rate Limit Label:** `Medium`",
    "operationId": "GetSmsSessions",
    "summary": "List user's SMS sessions in descending order"
   }
  },
  "/phone/users/{userId}/voice_mails": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Voicemails"
    ],
    "description": "Use this API to get a user's Zoom Phone voicemails. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:read`, `phone:read:admin`, `phone_voicemail:read`, `phone_voicemail:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoo[...]",
    "operationId": "phoneUserVoiceMails",
    "summary": "Get user's voicemails"
   }
  },
  "/phone/users/{userId}/voice_mails/sync": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Voicemails"
    ],
    "description": "Use this API to retrieve a user's Zoom Phone voicemails in descending order. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `phone:read`, `phone:read:admin`, `phone_voicemail:read`, `phone_voicemail:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Business or E[...]",
    "operationId": "GetPhoneUserVoiceMails",
    "summary": "List user's voicemails in descending order"
   }
  },
  "/phone/voice_mails": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Voicemails"
    ],
    "description": "Use this API to get a user's Zoom Phone voicemails. \n\n**Scopes:** `phone_voicemail:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license",
    "operationId": "accountVoiceMails",
    "summary": "Get account voicemails"
   }
  },
  "/phone/voice_mails/{voicemailId}": {
   "delete": {
    "tags": [
     "Voicemails"
    ],
    "description": "Use this API to delete an account's [voicemail message](https://support.zoom.us/hc/en-us/articles/360021400211-Managing-voicemail-messages).\n\n**Scopes:** `phone:write:admin`, `phone:write`, `phone_voicemail:write`, `phone_voicemail:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Zoom Phone license",
    "operationId": "deleteVoicemail",
    "summary": "Delete a voicemail"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Voicemails"
    ],
    "description": "Use this API to return information about a [voicemail message](https://support.zoom.us/hc/en-us/articles/360021400211-Managing-voicemail-messages).\n\n**Scopes:** `phone:read:admin`, `phone:read`, `phone_voicemail:read`, `phone_voicemail:read:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Zoom Phone license",
    "operationId": "getVoicemailDetails",
    "summary": "Get voicemail details"
   }
  },
  "/phone/dial_by_name_directory/extensions": {
   "post": {
    "tags": [
     "Dial by Name Directory"
    ],
    "description": "Use this API to add users to a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "AddUsersToDirectory",
    "summary": "Add users to a directory"
   },
   "get": {
    "tags": [
     "Dial by Name Directory"
    ],
    "description": "Use this API to get users that are in or not in a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:read:admin`\n\n**Rate Limit Label:** `Medium`",
    "operationId": "ListUsersFromDirectory",
    "summary": "List users in directory"
   },
   "delete": {
    "tags": [
     "Dial by Name Directory"
    ],
    "description": "Use this API to delete users from the [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "DeleteUsersFromDirectory",
    "summary": "Delete users from a directory"
   }
  },
  "/phone/sites/{siteId}/dial_by_name_directory/extensions": {
   "post": {
    "tags": [
     "Dial by Name Directory"
    ],
    "description": "Use this API to add users to a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory) of the specified site.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`\n",
    "operationId": "AddUsersToDirectoryBySite",
    "summary": "Add users to a directory of a site"
   },
   "get": {
    "tags": [
     "Dial by Name Directory"
    ],
    "description": "Use this API to get users that are in or not in a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory) of the specified site.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:read:admin`\n\n**Rate Limit Label:** `Medium`",
    "operationId": "ListUsersFromDirectoryBySite",
    "summary": "List users in a directory by site"
   },
   "delete": {
    "tags": [
     "Dial by Name Directory"
    ],
    "description": "Use this API to delete users from a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory) of the specified site.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "DeleteUsersFromDirectoryBySite",
    "summary": "Delete users from a directory of a site"
   }
  },
  "/phone/group_call_pickup": {
   "get": {
    "tags": [
     "Group Call Pickup"
    ],
    "description": "Use this API to retrieve a list of [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) objects in an account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listGCP",
    "summary": "List group call pickup objects"
   },
   "post": {
    "tags": [
     "Group Call Pickup"
    ],
    "description": "Use this API to add a [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) instance to the account that has the Zoom Phone license assigned. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addGCP",
    "summary": "Add a group call pickup object"
   }
  },
  "/phone/group_call_pickup/{groupId}": {
   "get": {
    "tags": [
     "Group Call Pickup"
    ],
    "description": "Use this API to retrieve information on a specific [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object in an account. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "GetGCP",
    "summary": "Get call pickup group by ID"
   },
   "patch": {
    "tags": [
     "Group Call Pickup"
    ],
    "description": "Use this API to update a specific [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object information.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "updateGCP",
    "summary": "Update the group call pickup information"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Group Call Pickup"
    ],
    "description": "Use this API to remove a [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteGCP",
    "summary": "Delete group call pickup objects"
   }
  },
  "/phone/group_call_pickup/{groupId}/members": {
   "get": {
    "tags": [
     "Group Call Pickup"
    ],
    "description": "Use this API to retrieve members of a [call pickup group](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) in an account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listGCPMembers",
    "summary": "List call pickup group members"
   },
   "post": {
    "tags": [
     "Group Call Pickup"
    ],
    "description": "Use this API to add members to the specified [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addGCPMembers",
    "summary": "Add members to a call pickup group"
   }
  },
  "/phone/group_call_pickup/{groupId}/members/{extensionId}": {
   "delete": {
    "tags": [
     "Group Call Pickup"
    ],
    "description": "Use this API to remove member from the [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "removeGCPMembers",
    "summary": "Remove members from call pickup group"
   }
  },
  "/phone/roles": {
   "get": {
    "tags": [
     "Phone Roles"
    ],
    "description": "Use this API to get phone roles.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:read:admin`\n\n**Rate Limit Label:** `Medium`",
    "operationId": "ListPhoneRoles",
    "summary": "List phone roles"
   },
   "post": {
    "tags": [
     "Phone Roles"
    ],
    "description": "Use this API to duplicate a phone role.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`\n",
    "operationId": "DuplicatePhoneRole",
    "summary": "Duplicate a phone role"
   }
  },
  "/phone/roles/{roleId}": {
   "delete": {
    "tags": [
     "Phone Roles"
    ],
    "description": "Use this API to delete a phone [role](https://support.zoom.us/hc/en-us/articles/360042099012-Using-Zoom-Phone-role-management).\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "DeletePhoneRole",
    "summary": "Delete a phone role"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Phone Roles"
    ],
    "description": "Use this API to get information on a phone [role](https://support.zoom.us/hc/en-us/articles/360042099012-Using-Zoom-Phone-role-management).\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:read:admin`\n\n**Rate Limit Label:** `Medium`",
    "operationId": "getRoleInformation",
    "summary": "Get role information"
   },
   "patch": {
    "tags": [
     "Phone Roles"
    ],
    "description": "Use this API to update a role.\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "UpdatePhoneRole",
    "summary": "Update a phone role"
   }
  },
  "/phone/roles/{roleId}/members": {
   "post": {
    "tags": [
     "Phone Roles"
    ],
    "description": "Use this API to add member(s) to a role.\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "AddRoleMembers",
    "summary": "Add members to a role"
   },
   "get": {
    "tags": [
     "Phone Roles"
    ],
    "description": "Use this API to get members (not) in a [role](https://support.zoom.us/hc/en-us/articles/360042099012-Using-Zoom-Phone-role-management).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:read:admin`\n\n**Rate Limit Label:** `Medium`",
    "operationId": "ListRoleMembers",
    "summary": "List members in a role"
   },
   "delete": {
    "tags": [
     "Phone Roles"
    ],
    "description": "Use this API to delete member(s) in a role.\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "DelRoleMembers",
    "summary": "Delete members in a role"
   }
  },
  "/phone/firmwares": {
   "get": {
    "tags": [
     "Firmware Update Rules"
    ],
    "description": "Use this API to get updatable [firmwares](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:read:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "ListFirmwares",
    "summary": "List updatable firmwares"
   }
  },
  "/phone/firmware_update_rules": {
   "post": {
    "tags": [
     "Firmware Update Rules"
    ],
    "description": "Use this API to add a [firmware update rule](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "AddFirmwareRule",
    "summary": "Add a firmware update rule"
   },
   "get": {
    "tags": [
     "Firmware Update Rules"
    ],
    "description": "Use this API to get [firmware update rules](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:read:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "ListFirmwareRules",
    "summary": "List firmware update rules"
   }
  },
  "/phone/firmware_update_rules/{ruleId}": {
   "get": {
    "tags": [
     "Firmware Update Rules"
    ],
    "description": "Use this API to get the [firmware update rule](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules) information.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:read:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "GetFirmwareRuleDetail",
    "summary": "Get firmware update rule information"
   },
   "delete": {
    "tags": [
     "Firmware Update Rules"
    ],
    "description": "Use this API to delete the [firmware update rule](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Scopes:** `phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "DeleteFirmwareUpdateRule",
    "summary": "Delete firmware update rule"
   },
   "patch": {
    "tags": [
     "Firmware Update Rules"
    ],
    "description": "Use this API to update a specific [firmware update rule](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n**Scopes:**`phone:write:admin`\n\n**Rate Limit Label:** `Light`",
    "operationId": "UpdateFirmwareRule",
    "summary": "Update firmware update rule"
   }
  },
  "/phone/billing_accounts": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Billing Account"
    ],
    "description": "A Zoom account owner or a user with admin privileges can use this API to retrieve a list of billing accounts.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n\n**Scope:** `phone:read:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listBillingAccount",
    "summary": "List billing accounts"
   }
  },
  "/phone/billing_accounts/{billingAccountId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Billing Account"
    ],
    "description": "A Zoom account owner or a user with admin privilege can use this API to get information about a billing account.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n\n**Scope:** `phone:read:admin` \n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "GetABillingAccount",
    "summary": "Get billing account details"
   }
  },
  "/phone/sms_campaigns": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "SMS Campaign"
    ],
    "description": "Use this API to list all SMS campaigns in a Zoom account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listAccountSMSCampaigns",
    "summary": "List SMS campaigns"
   }
  },
  "/phone/sms_campaigns/{smsCampaignId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "SMS Campaign"
    ],
    "description": "Use this API to get a specific SMS campaign.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "GetSMSCampaign",
    "summary": "Get an SMS campaign"
   }
  },
  "/phone/sms_campaigns/{smsCampaignId}/phone_numbers": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "SMS Campaign"
    ],
    "description": "Use this API to [assign a phone number to the SMS campaign](https://support.zoom.us/hc/en-us/articles/5016496738445-SMS-MMS-10DLC-Compliance-for-Zoom-Phone-and-Zoom-Contact-Center#h_01FYVVQM1WMW5JD48YNY3J581B).\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "assignCampaignPhoneNumbers",
    "summary": "Assign a phone number to SMS campaign"
   }
  },
  "/phone/sms_campaigns/{smsCampaignId}/phone_numbers/{phoneNumberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "SMS Campaign"
    ],
    "description": "Use this API to [unassign a phone number from the SMS campaign](https://support.zoom.us/hc/en-us/articles/5016496738445-SMS-MMS-10DLC-Compliance-for-Zoom-Phone-and-Zoom-Contact-Center#h_01FYVVSPVM8MZN4Y9EW5690QHH).\nRemove the assigned phone number from the campaign.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license \n* The campaign must have been previously assigned a Zoom Phone number\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Labe[...]",
    "operationId": "unassignCampaignPhoneNumber",
    "summary": "Unassign a phone number"
   }
  },
  "/phone/provision_templates": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Provision Templates"
    ],
    "description": "Use this API to list all [provision templates](https://support.zoom.us/hc/en-us/articles/360035817952) in a Zoom account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listAccountProvisionTemplate",
    "summary": "List provision templates"
   },
   "post": {
    "tags": [
     "Provision Templates"
    ],
    "description": "Use this API to [create a provision template](https://support.zoom.us/hc/en-us/articles/360035817952#h_8266cb40-58fc-4c1a-8da2-885d72167234) in a Zoom account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addProvisionTemplate",
    "summary": "Add a provision template"
   }
  },
  "/phone/provision_templates/{templateId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Provision Templates"
    ],
    "description": "Use this API to get a specific [provision template](https://support.zoom.us/hc/en-us/articles/360035817952).\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "GetProvisionTemplate",
    "summary": "Get a provision template"
   },
   "patch": {
    "tags": [
     "Provision Templates"
    ],
    "description": "Use this API to update a [provision template](https://support.zoom.us/hc/en-us/articles/360035817952#h_7b34cd1d-5ae6-4a23-bd04-454a6ad8cb3e) in a Zoom account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "updateProvisionTemplate",
    "summary": "Update a provision template"
   },
   "delete": {
    "tags": [
     "Provision Templates"
    ],
    "description": "Use this API to [delete a provision template](https://support.zoom.us/hc/en-us/articles/360035817952#h_7b34cd1d-5ae6-4a23-bd04-454a6ad8cb3e) in a Zoom account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**Scopes:** `phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteProvisionTemplate",
    "summary": "Delete a provision template"
   }
  },
  "/phone/devices/{deviceId}/provision_templates": {
   "put": {
    "tags": [
     "Phone Devices"
    ],
    "description": "Use this API to [assign a provision template to a device](https://support.zoom.us/hc/en-us/articles/360035817952#h_6b52ef26-d070-40ed-a3fa-520571944afc) or [remove a provision template from the device](https://support.zoom.us/hc/en-us/articles/360035817952#h_7b34cd1d-5ae6-4a23-bd04-454a6ad8cb3e) by leaving `templateId` empty.\n\n**Prerequisites:**<br>\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n* [Supported device](https://support[...]",
    "operationId": "updateProvisionTemplateToDevice",
    "summary": "Update provision template of a device"
   }
  }
 },
 "components": {
  "securitySchemes": {
   "Bearer": {
    "in": "header",
    "name": "Authorization",
    "type": "apiKey"
   },
   "Client_Credentials": {
    "description": "Client Credentials Flow for ChatBots",
    "flows": {
     "clientCredentials": {
      "scopes": {},
      "tokenUrl": "https://api.zoom.us/oauth/token"
     }
    },
    "type": "oauth2"
   },
   "OAuth": {
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://zoom.us/oauth/authorize",
      "scopes": {},
      "tokenUrl": "https://zoom.us/oauth/token"
     }
    },
    "type": "oauth2"
   }
  }
 },
 "security": [
  {
   "OAuth": []
  }
 ],
 "tags": [
  {
   "name": "Accounts"
  },
  {
   "name": "Audio Library"
  },
  {
   "name": "Auto Receptionists"
  },
  {
   "name": "Billing Account"
  },
  {
   "name": "Blocked List"
  },
  {
   "name": "Call Handling"
  },
  {
   "name": "Call Logs"
  },
  {
   "name": "Call Queues"
  },
  {
   "name": "Carrier Reseller"
  },
  {
   "name": "Common Area Phones",
   "description": "The API will be deprecated in January, 2023. See the [API announcements](https://marketplace.zoom.us/docs/guides/stay-up-to-date/upcoming-changes/api/), [Zoom support article](https://support.zoom.us/hc/en-us/articles/4481136653709-May-2022-New-Common-Area-Experience) and [release notes](https://marketplace.zoom.us/docs/guides/stay-up-to-date/changelog/) for more information."
  },
  {
   "name": "Common Areas",
   "description": "For customers who opted for `Common Area Optimization`. See the [API announcements](https://marketplace.zoom.us/docs/guides/stay-up-to-date/upcoming-changes/api/), [Zoom support article](https://support.zoom.us/hc/en-us/articles/4481136653709-May-2022-New-Common-Area-Experience) and [release notes](https://marketplace.zoom.us/docs/guides/stay-up-to-date/changelog/) for more information."
  },
  {
   "name": "Dashboard"
  },
  {
   "name": "Phone Devices"
  },
  {
   "name": "Device Line Keys"
  },
  {
   "name": "Dial by Name Directory"
  },
  {
   "name": "Directory Backup Routing Rules"
  },
  {
   "name": "Emergency Service Locations"
  },
  {
   "name": "Emergency Addresses"
  },
  {
   "name": "External Contacts"
  },
  {
   "name": "Firmware Update Rules"
  },
  {
   "name": "Group Call Pickup",
   "description": "[Group call pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) operations"
  },
  {
   "name": "IVR"
  },
  {
   "name": "Line Keys"
  },
  {
   "name": "Monitoring Groups"
  },
  {
   "name": "Phone Numbers"
  },
  {
   "name": "Phone Plans"
  },
  {
   "name": "Provider Exchange"
  },
  {
   "name": "Provision Templates"
  },
  {
   "name": "Recordings"
  },
  {
   "name": "Reports"
  },
  {
   "name": "Phone Roles"
  },
  {
   "name": "Settings"
  },
  {
   "name": "Setting Templates"
  },
  {
   "name": "Shared Line Appearance"
  },
  {
   "name": "Shared Line Group"
  },
  {
   "name": "Sites"
  },
  {
   "name": "SMS"
  },
  {
   "name": "SMS Campaign"
  },
  {
   "name": "Users"
  },
  {
   "name": "Voicemails"
  },
  {
   "name": "Zoom Rooms"
  }
 ]
}